//! Class A — pure local, reversible effect trait.
//!
//! Class A effects act **only** on the View's `delta` layer.  They have no
//! observable consequence outside the system and are reversed by Delta discard
//! at `abort`.  Class A effects do **NOT** enter `View.effects_hash`.
//!
//! # Enforcement
//!
//! The trait method [`ClassA::apply`] produces a single [`reel_spec::Op`]
//! (a `Delta::Op`).  Because no `Capability` or I/O handle appears in the
//! signature, a `ClassA` implementation **cannot** perform network or
//! filesystem I/O in safe Rust — the type system enforces isolation
//! (L1 per
//! effect-class-rules § 5).
//!
//! # Sealing
//!
//! The trait is sealed via `crate::sealed::Sealed`.  Because `Sealed` lives
//! in the `pub(crate) sealed` module, external crates cannot reach it and
//! therefore cannot `impl ClassA`; they must use the `#[reel::class_a]`
//! proc-macro which generates the `impl Sealed` + `impl ClassA` pair
//! inside this crate.
//!
//! # References
//!
//! - Wang & Zheng, "Fork, Explore, Commit", arXiv 2602.08199v2 § 4.3.
//! - ADR-0003 (effect class taxonomy).
//! - ADR-0025 (canonical ontology).

use crate::sealed::Sealed;
use reel_spec::Op;

/// Class A — pure local, reversible effect.
///
/// Implementations MUST act only on the View's delta layer — no network
/// calls, no filesystem operations outside the View's scope, no process
/// spawning.  The absence of any capability or runtime handle in the
/// method signature is the machine-checkable proof of this restriction
/// (L1 isolation).
///
/// # Examples
///
/// `Sealed` is `pub(crate)`, so external crates cannot write
/// `impl ClassA` directly; they must use the `#[reel::class_a]`
/// proc-macro.  Runnable proof for the in-crate path is in
/// the unit-test suite (`lib.rs::tests::class_a_produces_put_op`).
///
/// ```rust,ignore
/// use reel_effects::ClassA;
/// use reel_spec::{Hash, Op};
///
/// // In a real crate this is generated by #[reel::class_a].
/// #[reel::class_a]
/// struct PutEntry { name: String, hash: Hash }
///
/// impl ClassA for PutEntry {
///     fn apply(&self) -> Op {
///         Op::Put {
///             name: self.name.clone(),
///             hash: self.hash,
///         }
///     }
/// }
///
/// let eff = PutEntry {
///     name: "docs/readme.md".into(),
///     hash: Hash::from_bytes([0u8; 32]),
/// };
/// let op = eff.apply();
/// assert!(matches!(op, Op::Put { .. }));
/// ```
pub trait ClassA: Sealed + Send + 'static {
    /// Apply this effect, producing the [`Op`] to append to the View's
    /// [`reel_spec::Delta`].
    ///
    /// # Cancel Safety
    ///
    /// Synchronous; trivially cancel-safe.
    fn apply(&self) -> Op;
}
