name        = "slack"
class       = "C"
scope       = "slack:*"
version     = "0.1.0"
reel-target = "v0.1"

[capabilities]
ops = ["post_message", "edit_message", "delete_message"]

[conformance]
last-tested = "2026-05-22"
level       = 1
