//! Class C Slack messaging adapter for the reel protocol.
//!
//! `adapter-slack` is the **demo Class C adapter** that proves reel's
//! I-002 guarantee: a Slack message buffered by a View that is later
//! `abort`ed is never sent.
//!
//! # Overview
//!
//! [`SlackAdapter`] wraps a [`SlackTransport`] and offers three
//! constructor methods that produce
//! [`reel_spec::EffectDescriptor::C`] entries:
//!
//! | Method | Slack Web API |
//! |--------|---------------|
//! | [`SlackAdapter::post_message`]   | `chat.postMessage` |
//! | [`SlackAdapter::edit_message`]   | `chat.update`      |
//! | [`SlackAdapter::delete_message`] | `chat.delete`      |
//!
//! The descriptors are buffered by the kernel inside
//! `View.effects_hash`. At commit time the kernel calls
//! [`SlackAdapter::fire`] for each descriptor, supplying the View's
//! [`reel_spec::Capability`]. The adapter then validates the capability
//! and dispatches the operation through the transport.
//!
//! # Why not `impl ClassC`?
//!
//! `reel_effects::ClassC` is a **sealed in-process trait** (per
//! `effect-class-rules.md` § 5 + ADR-0025 ontology). External adapters
//! cannot — and do not need to — implement it directly. The kernel
//! constructs `reel_effects::BoxedC` from in-tree effect types
//! generated by the `#[reel::class_c]` proc-macro; this
//! adapter sits one level above that, mapping wire-format
//! [`reel_spec::EffectDescriptor::C`] descriptors back to live
//! [`SlackOp`] values at commit time.
//!
//! # Sealing & I-003 enforcement
//!
//! [`SlackAdapter::fire`] inspects the supplied capability and rejects
//! with E-009 ([`reel_spec::ReelError::CapabilityViolation`]) on any of:
//!
//! - `OpKind::FireC` ∉ `op_set`
//! - channel target outside `path_prefix`
//! - ttl semantics violated (current policy: `ttl == 0` ⇒ unbounded;
//!   non-zero ttl passes the static check; real wall-clock expiry is
//!   plumbed in a follow-up task)
//!
//! See `SlackAdapter::check_capability` for the source of truth.
//!
//! # Testing
//!
//! All adapter-level tests use [`MockTransport`]. **No unit test
//! performs real HTTP**, per the discipline that the adapter must be
//! exerciseable without a Slack workspace. The real HTTP transport
//! will land behind a cargo feature in a follow-up task.
//!
//! # References
//!
//! - `spec/spec.md` § 5.7 (effect classes), § 10 (logging discipline).
//! - `spec/adapter-interface.md` (adapter trait shape).
//! - the design notes,
//!   `0006-effect-isolation-layers.md`,
//!   `0025-six-types-three-verbs-three-invariants.md`.
//! - the design notes.

#![allow(
    clippy::multiple_crate_versions,
    clippy::lint_groups_priority,
    reason = "pre-existing workspace configuration issues"
)]
#![deny(rustdoc::broken_intra_doc_links)]
#![deny(rustdoc::private_intra_doc_links)]
#![warn(rustdoc::bare_urls)]
#![warn(missing_docs)]
#![doc(test(attr(deny(warnings))))]

mod adapter;
mod error;
mod op;
mod transport;

pub use adapter::{SLACK_PATH_PREFIX_BASE, SlackAdapter};
pub use error::SlackError;
pub use op::SlackOp;
pub use transport::{MockTransport, SlackTransport, TransportRecord};

#[cfg(test)]
#[allow(
    clippy::panic,
    clippy::unwrap_used,
    clippy::missing_assert_message,
    reason = "test assertions intentionally panic on failure"
)]
mod tests {
    use super::*;
    use reel_spec::{Capability, EffectDescriptor, OpKind, ReelError};
    use std::collections::BTreeSet;

    fn full_cap() -> Capability {
        Capability {
            path_prefix: format!("{SLACK_PATH_PREFIX_BASE}#"),
            op_set: BTreeSet::from([OpKind::FireC]),
            ttl: 0,
        }
    }

    fn narrowed_cap_to_general() -> Capability {
        Capability {
            path_prefix: format!("{SLACK_PATH_PREFIX_BASE}#general"),
            op_set: BTreeSet::from([OpKind::FireC]),
            ttl: 0,
        }
    }

    fn op_field<'a>(descriptor: &'a EffectDescriptor, key: &str) -> &'a serde_json::Value {
        let EffectDescriptor::C { op, .. } = descriptor else {
            panic!("expected Class C descriptor, got {descriptor:?}");
        };
        op.get(key).unwrap_or_else(|| panic!("missing op key {key}"))
    }

    // ─────────────────────────────────────────────────────────────────
    // Descriptor construction
    // ─────────────────────────────────────────────────────────────────

    #[test]
    fn post_message_builds_class_c_descriptor() {
        let adapter = SlackAdapter::new(MockTransport::new());
        let descriptor = adapter
            .post_message("#general", "deploy done")
            .unwrap_or_else(|e| panic!("post_message failed: {e}"));
        let EffectDescriptor::C { effect_id, .. } = descriptor else {
            panic!("expected Class C descriptor, got {descriptor:?}");
        };
        assert_eq!(effect_id, 0, "first descriptor uses id 0");
        assert_eq!(op_field(&descriptor, "action"), &serde_json::json!("post_message"));
        assert_eq!(op_field(&descriptor, "channel"), &serde_json::json!("#general"));
        assert_eq!(op_field(&descriptor, "text"), &serde_json::json!("deploy done"));
    }

    #[test]
    fn distinct_descriptors_have_distinct_effect_ids() {
        let adapter = SlackAdapter::new(MockTransport::new());
        let d0 = adapter.post_message("#a", "x").unwrap_or_else(|e| panic!("{e}"));
        let d1 = adapter.edit_message("#a", "1.0", "y").unwrap_or_else(|e| panic!("{e}"));
        let d2 = adapter.delete_message("#a", "1.0").unwrap_or_else(|e| panic!("{e}"));
        for (i, descriptor) in [&d0, &d1, &d2].iter().enumerate() {
            let EffectDescriptor::C { effect_id, .. } = descriptor else {
                panic!("expected Class C, got {descriptor:?}");
            };
            assert_eq!(u64::try_from(i).unwrap(), *effect_id, "effect_id monotone");
        }
    }

    #[test]
    fn edit_and_delete_are_distinct_class_c_actions() {
        let adapter = SlackAdapter::new(MockTransport::new());
        let edit = adapter.edit_message("#a", "1.0", "new").unwrap_or_else(|e| panic!("{e}"));
        let del = adapter.delete_message("#a", "1.0").unwrap_or_else(|e| panic!("{e}"));
        assert_eq!(op_field(&edit, "action"), &serde_json::json!("edit_message"));
        assert_eq!(op_field(&del, "action"), &serde_json::json!("delete_message"));
        assert_ne!(op_field(&edit, "action"), op_field(&del, "action"));
    }

    // ─────────────────────────────────────────────────────────────────
    // describe_preview — spec.md §5.7.3 + §10
    // ─────────────────────────────────────────────────────────────────

    #[test]
    fn preview_includes_channel_and_action_no_token() {
        let adapter = SlackAdapter::new(MockTransport::new());
        let descriptor = adapter
            .post_message("#general", "secret deploy plan")
            .unwrap_or_else(|e| panic!("{e}"));
        let preview = SlackAdapter::<MockTransport>::describe_preview(&descriptor)
            .unwrap_or_else(|e| panic!("{e}"));
        assert_eq!(preview.get("channel"), Some(&serde_json::json!("#general")));
        assert_eq!(preview.get("action"), Some(&serde_json::json!("post_message")));
        let preview_str = preview.to_string();
        assert!(!preview_str.to_lowercase().contains("xoxb"), "token leak");
    }

    #[test]
    fn preview_redacts_long_text() {
        let adapter = SlackAdapter::new(MockTransport::new());
        let long = "a".repeat(200);
        let descriptor = adapter.post_message("#a", long).unwrap_or_else(|e| panic!("{e}"));
        let preview = SlackAdapter::<MockTransport>::describe_preview(&descriptor)
            .unwrap_or_else(|e| panic!("{e}"));
        let excerpt = preview
            .get("text_excerpt")
            .and_then(serde_json::Value::as_str)
            .unwrap_or_else(|| panic!("text_excerpt missing or wrong type"));
        assert!(excerpt.ends_with('…'), "long text should be truncated, got: {excerpt}");
        assert!(
            excerpt.chars().count() <= 81,
            "redacted excerpt longer than 80+ellipsis: {} chars",
            excerpt.chars().count()
        );
    }

    // ─────────────────────────────────────────────────────────────────
    // I-003 invariant proof — positive
    // ─────────────────────────────────────────────────────────────────

    #[tokio::test]
    async fn fire_succeeds_with_narrowed_cap_to_general() {
        let adapter = SlackAdapter::new(MockTransport::new());
        let descriptor =
            adapter.post_message("#general", "hello").unwrap_or_else(|e| panic!("{e}"));
        let cap = narrowed_cap_to_general();
        let record = adapter
            .fire(&descriptor, &cap)
            .await
            .unwrap_or_else(|e| panic!("expected fire ok: {e}"));
        assert_eq!(record.message_ts, "1700000000.000100", "default mock ts");
        assert_eq!(adapter.transport().send_count(), 1, "one send dispatched");
    }

    #[tokio::test]
    async fn fire_succeeds_with_root_cap_full_prefix() {
        let adapter = SlackAdapter::new(MockTransport::new());
        let descriptor =
            adapter.post_message("#general", "hello").unwrap_or_else(|e| panic!("{e}"));
        let cap = full_cap();
        adapter.fire(&descriptor, &cap).await.unwrap_or_else(|e| panic!("expected fire ok: {e}"));
        assert_eq!(adapter.transport().send_count(), 1, "one send dispatched");
    }

    // ─────────────────────────────────────────────────────────────────
    // I-003 invariant proof — negative — op_set lacking FireC
    // ─────────────────────────────────────────────────────────────────

    #[tokio::test]
    async fn fire_rejects_capability_without_fire_c_op() {
        let adapter = SlackAdapter::new(MockTransport::new());
        let descriptor =
            adapter.post_message("#general", "hello").unwrap_or_else(|e| panic!("{e}"));
        let cap_no_fire_c = Capability {
            path_prefix: format!("{SLACK_PATH_PREFIX_BASE}#general"),
            op_set: BTreeSet::from([OpKind::Read, OpKind::Write]),
            ttl: 0,
        };
        let err = adapter.fire(&descriptor, &cap_no_fire_c).await;
        assert!(
            matches!(err, Err(ReelError::CapabilityViolation(_))),
            "expected E-009 CapabilityViolation, got {err:?}"
        );
        assert_eq!(
            adapter.transport().send_count(),
            0,
            "transport never invoked when capability check fails"
        );
    }

    // ─────────────────────────────────────────────────────────────────
    // I-003 invariant proof — negative — path outside narrowed prefix
    // ─────────────────────────────────────────────────────────────────

    #[tokio::test]
    async fn fire_rejects_channel_outside_narrowed_prefix() {
        let adapter = SlackAdapter::new(MockTransport::new());
        let descriptor = adapter.post_message("#secret", "leak").unwrap_or_else(|e| panic!("{e}"));
        let cap = narrowed_cap_to_general();
        let err = adapter.fire(&descriptor, &cap).await;
        assert!(
            matches!(err, Err(ReelError::CapabilityViolation(_))),
            "expected E-009 CapabilityViolation, got {err:?}"
        );
        assert_eq!(
            adapter.transport().send_count(),
            0,
            "transport never invoked when channel is outside narrowed prefix"
        );
    }

    // ─────────────────────────────────────────────────────────────────
    // Sealing — descriptor decode rejects non-C descriptors
    // ─────────────────────────────────────────────────────────────────

    #[tokio::test]
    async fn fire_rejects_non_class_c_descriptor() {
        let adapter = SlackAdapter::new(MockTransport::new());
        let class_a = EffectDescriptor::A { effect_id: 99, op: serde_json::json!({"x": 1}) };
        let cap = narrowed_cap_to_general();
        let err = adapter.fire(&class_a, &cap).await;
        assert!(matches!(err, Err(ReelError::Storage(_))), "expected E-007, got {err:?}");
    }

    // ─────────────────────────────────────────────────────────────────
    // Transport error mapping
    // ─────────────────────────────────────────────────────────────────

    #[tokio::test]
    async fn transport_timeout_maps_to_e006() {
        let mock = MockTransport::new().with_responses(vec![Err(SlackError::Timeout)]);
        let adapter = SlackAdapter::new(mock);
        let descriptor =
            adapter.post_message("#general", "hello").unwrap_or_else(|e| panic!("{e}"));
        let err = adapter.fire(&descriptor, &narrowed_cap_to_general()).await;
        assert!(matches!(err, Err(ReelError::EffectDrainTimeout)), "expected E-006, got {err:?}");
    }

    #[tokio::test]
    async fn transport_api_error_maps_to_e007() {
        let mock =
            MockTransport::new().with_responses(vec![Err(SlackError::Api("invalid_auth".into()))]);
        let adapter = SlackAdapter::new(mock);
        let descriptor =
            adapter.post_message("#general", "hello").unwrap_or_else(|e| panic!("{e}"));
        let err = adapter.fire(&descriptor, &narrowed_cap_to_general()).await;
        assert!(matches!(err, Err(ReelError::Storage(_))), "expected E-007, got {err:?}");
    }

    // ─────────────────────────────────────────────────────────────────
    // check_capability — direct entry (used by external test harness
    // for the t_004 conformance vector once it lands)
    // ─────────────────────────────────────────────────────────────────

    #[test]
    fn check_capability_rejects_narrowed_path_amplification() {
        let op = SlackOp::PostMessage { channel: "#other".into(), text: "x".into() };
        let result =
            SlackAdapter::<MockTransport>::check_capability(&op, &narrowed_cap_to_general());
        assert!(
            matches!(result, Err(SlackError::CapabilityDenied(_))),
            "expected CapabilityDenied, got {result:?}"
        );
    }

    #[test]
    fn check_capability_accepts_full_namespace_prefix() {
        let op = SlackOp::PostMessage { channel: "#general".into(), text: "x".into() };
        let result = SlackAdapter::<MockTransport>::check_capability(&op, &full_cap());
        result.unwrap_or_else(|e| panic!("expected ok, got {e}"));
    }

    // ─────────────────────────────────────────────────────────────────
    // Conformance proxy — t_004 "abort discards Class C"
    // ─────────────────────────────────────────────────────────────────
    //
    // The kernel-driven t_004 test lands with reel-core commit/abort.
    // Here we prove the static reachability claim: when a descriptor
    // is buffered but never passed to fire(), the transport remains
    // untouched. This is the I-002 enforcement at the adapter layer.

    #[tokio::test]
    async fn abort_path_never_invokes_transport_t_004_proxy() {
        let adapter = SlackAdapter::new(MockTransport::new());
        let descriptor =
            adapter.post_message("#general", "should never send").unwrap_or_else(|e| panic!("{e}"));
        assert_eq!(adapter.transport().send_count(), 0, "no fire() means no transport.send()");
        assert!(matches!(descriptor, EffectDescriptor::C { .. }));
    }
}
